### ISSUE TITLE
Style per new ish site

### ISSUE THREAD

**Issue by ari** [ishgroup/lightbook#1]
Pick up the fonts and colours from the new site. Use the dark grey colour as per the sidebar (and also used in the Jira top bar) for the top menu.

Tighten up the list of results so we can get more per page.

Review responsive design.

**Comment by ari** [comment]
This is not bad. Some more things:

[ ] Remove bug from logo in top left (that's for squish)
[ ] Make the search results much more compact so we get twice as many on a page (roughly)

**Comment by chintankotadia** [comment]
This is done
