### ISSUE TITLE
Mailchimp Integration with phone.ish

### ISSUE THREAD

**Issue by meganish** [ishgroup/lightbook#13]
Add checkbox or dropdown to UI so we can easily add contacts to our mailing lists. 

We could use the same layout mailchimp currently has to make it simple
![screen shot 2016-11-24 at 10 04 40 am](https://cloud.githubusercontent.com/assets/19790509/20581519/850fa120-b22d-11e6-9f5c-9497933b28eb.png)

**Comment by ari** [comment]
Let's come back to mailchimp later.
