### ISSUE TITLE
Add, Update & Delete are throwing error for company and people

### ISSUE THREAD

**Issue by chintankotadia** [ishgroup/lightbook#19]
Hi @k41n 

Can you please look into this one? You'll need to include options for these call. Please take a look at development.py for calls.

Thanks!

**Comment by k41n** [comment]
@chintankotadia, you need to be authenticated before doing modification in ldap. I implemented basic auth, but I'm not sure that all users have necessary permissions.
@ari, I have a issue with addition people/companies in ldap. We need to store maximum uidNumber and uniqueIdentifier somewhere in ldap, because we need unique dn in order to create ldap entry.

**Comment by k41n** [comment]
Also for adding a person he needs to send "password".
As for company I need LDAP mapping for next fields:
"address"
"suburb"
"postal"
"country"

**Comment by ari** [comment]
I've fixed authentication in the LDAP server now. All employees have read-write access so please be careful with testing against the live db.

**Comment by k41n** [comment]
@ari, I created "cn=counts,dc=ish,dc=com,dc=au" in order to store max uidNumber and uniqueIdentifier.
Please, give permissions to employees to change cn=maxUidNumber,cn=counts,dc=ish,dc=com,dc=au, cn=maxUniqueIdentifier,cn=counts,dc=ish,dc=com,dc=au.

**Comment by ari** [comment]
Done. How do we reset this number if it gets out of sync? Can the code be self healing in that it catches the error if we try to write a duplicate and then increments the maxid until it finds a free one?

**Comment by k41n** [comment]
I implemented this approach.
Could you check next company fields:
"address"
"suburb"
"postal"
"country"
How should I map them with attributes in ldap?

**Comment by chintankotadia** [comment]
@k41n : Add and update are not working. I found the reason behind the issue. You'll can get the requested data using `request.get_data()` instead of [`request.json`](https://github.com/ishgroup/lightbook/blob/master/production.py#L51). `request.json` won't be able to retrieve the data sent from client side in serialize json form. At the moment, `request.json` is trying to find `json` key. Can you please look into it?

Thanks!

**Comment by meganish** [comment]
`Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/var/lightbook/ldap_api/ldap_auth.py", line 15, in decorated return f(*args, **kwargs) File "/var/lightbook/production.py", line 169, in add_person "people": get_ldap_api().add_person(request.json) File "/var/lightbook/ldap_api/ldap_api.py", line 168, in add_person ldap_attributes['userPassword'] = attributes['password'] KeyError: 'password'`

**Comment by meganish** [comment]
Tried to Edit a contact - nothing happening when I clicked 'Update'

Added a new user and got an error when I selected 'Add People'
![screen shot 2016-12-09 at 9 21 00 am](https://cloud.githubusercontent.com/assets/19790509/21030107/ed0becce-bdf0-11e6-9198-f825002ba692.png)

**Comment by meganish** [comment]
@k41n  please resolve this today as your priority. 

Thanks

**Comment by meganish** [comment]
it should be not compulsory for all the fields to have content when adding a new contact

**Comment by meganish** [comment]
successfully added people. Thanks
