### ISSUE TITLE
Handling phone number

### ISSUE THREAD

**Issue by chintankotadia** [ishgroup/lightbook#20]
@ari, Phones are containing string i.e. number along with label. Labels are uneven. Can you please let me know, how we are going to handle this one?

**Comment by ari** [comment]
Remove the clickable action in the edit view. It makes it too hard to edit the phone field.

Don't worry about the string. We can tidy them up later if we need to.

**Comment by ari** [comment]
I think I fixed this. Chintan, please review and confirm.
