### ISSUE TITLE
People: show email

### ISSUE THREAD

**Issue by meganish** [ishgroup/lightbook#24]
When looking at a contact record, the email field is not filling with an email address. Is it marked as 'mail' or something similar in LDAP and not displaying?
![screen shot 2016-12-07 at 3 27 18 pm](https://cloud.githubusercontent.com/assets/19790509/20954718/d27d6064-bc91-11e6-9529-84bcd93a3f6e.png)

**Comment by chintankotadia** [comment]
@k41n : Can you please look into it asap? I did some debugging and found that email is not added in [mapping](https://github.com/ishgroup/lightbook/blob/master/ldap_api/ldap_api.py#L10) constant.

**Comment by k41n** [comment]
@chintankotadia, I added email field to mapping.

**Comment by meganish** [comment]
The email field has always been available - but the actual email for the contact is not showing. For the above example, the email should show garry.traynor@sydneycommunitycollege.edu.au

**Comment by meganish** [comment]
Sorry, is fixed. Thanks
