### ISSUE TITLE
Company -> show people

### ISSUE THREAD

**Issue by ari** [ishgroup/lightbook#6]
When looking at a company record, we need a list of people at that company. You can click on each person to take you to their record.

**Comment by ari** [comment]
@k41n Can we have this list in alphabetical order.

http://osdir.com/ml/python-ldap/2009-05/msg00015.html

**Comment by ari** [comment]
Chintan, the company detail page has a list of people which is nice, but it is missing the details of the company itself.

**Comment by chintankotadia** [comment]
@ari : This is done. Thanks!
